# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '20 4 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 14
        stale-issue-message: 'This issue appears to be stale. We will automatically close it within 30 days of no more activity recorded.'
        stale-pr-message: 'This pull request appear to be stale. We will automatically close it within 60 days of no more activity recorded.'
        stale-issue-label: '1 | state: waiting for reporter feedback'
        stale-pr-label: '1 | state: waiting for reporter feedback'
        days-before-close: 60
        days-before-issue-close: 30
        close-issue-message: >
          This issue has been automatically closed because there has been no response
          to our request for more information from the original author. With only the
          information that is currently in the issue, we don't have enough information
          to take action. Please reach out if you have or find the answers we need so
          that we can investigate further.
        close-pr-message: >
          This pull request has been automatically closed because there has been no
          activity from the original author. Please reach out if you have or find the
          answers we need so that we can investigate further.
